### ISSUE TITLE
De-dupe work on xAPI transforms

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/openedx-oars#12]
We currently have 2 diverging implementations of xAPI transforms of tracking log events. 

Can we work together to make one set of transforms that can be shared? Can we have the best of both worlds- anonymous actor ids from event-routing-backends, tracking log replay from Ralph?

Once we have a better understanding of what the source of truth for these transforms are we'll be in a better place to tackle this:

- [ ] https://github.com/openedx/openedx-oars/issues/18

**Comment by bmtcril** [comment]
I'm hoping to get buy in from Data WG team members on this tomorrow. 🤞

**Comment by bmtcril** [comment]
Invested parties are getting together on 2023-01-17 to discuss the first round of questions and decide whether this should be an ongoing sub-group or of some lighter way of working together is better.

**Comment by pomegranited** [comment]
Awesome, thank you for raising this issue and scheduling this meeting @bmtcril !
Are there meeting notes or recording anywhere, or a group page on Confluence I can follow?

**Comment by bmtcril** [comment]
The notes and action items are here, though we didn't come to a lot of decisions yet. Zia and I are getting more familiar with the Pydantic implementation and will round up soon to chat about our findings.
