### ISSUE TITLE
Investigation: Ralph / ClickHouse Integration

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/openedx-oars#13]
Work with FUN to specify a ClickHouse backend for Ralph that meets the performance needs of querying along various xAPI statement types.

AC:
- Questions answered about what an implementation would need to do for it to be acceptable to FUN and usable for this project, answers in this ticket are fine, it's just to get to a common understanding

**Comment by bmtcril** [comment]
I'm working on the branch here: https://github.com/bmtcril/ralph/pull/2

Still a ways to go 😄

**Comment by bmtcril** [comment]
I've sent a list of questions to FUN about things I saw when working with Ralph, and am hoping we can meet up soon to discuss. From there I think we'll be able to make long term decisions about using it and ticket any work on our side to get ClickHouse integration over the line.

**Comment by bmtcril** [comment]
Merged here: https://github.com/openfun/ralph/pull/274
