### ISSUE TITLE
Users can view how many times each section of each video was watched

### ISSUE THREAD

**Issue by crathbun428** [openedx/openedx-oars#139]
**User Story**
As a course author, I want to see how many times each section of each video in my course was viewed, so that I can identify segments of video that are either really important or potentially unclear.

**Acceptance Criteria**
Scenario: A course author can see the number of times each 5 second segment of video was watched for each video in their course
**Given I** am a course author with X permissions
**When I** view the course engagement section of the course dashboard
**Then I** can view the number of times each 5 second segment of video was watched for each video in my course

**Comment by SoryRawyer** [comment]
I think this can be charted using the [`fact_watched_video_segments` dataset](https://github.com/openedx/tutor-contrib-aspects/blob/main/tutoraspects/templates/aspects/build/aspects-superset/openedx-assets/assets/datasets/fact_watched_video_segments.yaml) in Superset.
