### ISSUE TITLE
Spike: Integrate Superset with Clickhouse storing xAPI events

### ISSUE THREAD

**Issue by pomegranited** [openedx/openedx-oars#30]
With https://github.com/openedx/data-wg/issues/21, we created a [Tutor plugin to deploy Superset](https://github.com/open-craft/tutor-contrib-superset/) integrated to the Open edX SSO and MySQL database, and worked out how to restrict access to data based on course roles.

Ultimately, the reference implementation of Open edX Analytics will use an LRS (e.g. Ralph) to store xAPI events in Clickhouse. So we need Superset to read xAPI events from Clickhouse.

This ticket involves these different repositories:
* [Tutor Superset plugin](https://github.com/open-craft/tutor-contrib-superset/) -- Apache Superset, with customisations for Open edX
* [Tutor Clickhouse plugin](https://github.com/bmtcril/tutor-contrib-clickhouse) -- installs Clickhouse
* [OARS](https://github.com/openedx/openedx-oars) -- glue that ties all of the analytics plugins together.

**Acceptance criteria**

* Plugin(s) add a Clickhouse Data Source to Superset,  ref https://superset.apache.org/docs/databases/clickhouse/
* Configurable option to pre-populate Clickhouse with a large xAPI data set, containing Open edX events, ref https://github.com/bmtcril/xapi-db-load
* Plugin(s) add query templates to Superset to enforce course role permissions when reading xAPI events from Clickhouse.
* Plugin(s) add a Chart to Superset that creates a simple demonstration of the above xAPI events and course access permissions (can be basic).
* Update OARS plugin README / docs to point to all of these plugins.

**Comment by bmtcril** [comment]
Looks great, I've moved it to the OARS board and set it ready for work so if you get a chance to pick it up you're good to go.

**Comment by pomegranited** [comment]
assign me

**Comment by pomegranited** [comment]
@bmtcril Github wouldn't assign me :( Maybe because I created this ticket?

**Comment by bmtcril** [comment]
Could be that the action isn't installed on this repo. I'll round up and try to figure it out, but have assigned it to you in the meantime. Thanks for picking it up!

**Comment by pomegranited** [comment]
Ideas about what goes where:

* Superset plugin needs to hold the python dependencies and custom code, because it needs to be loaded when Superset runs.
* Clickhouse plugin should just load Clickhouse into the Tutor environment, with whatever minimal customizations are needed to access it from within Tutor.
* OARS plugin should store any Open edX-specific scripts that invoke the Superset API, or data that can be loaded into Clickhouse.
* All dev data should not be loaded by default; enable a Tutor env variable in order to trigger loading.

**Comment by pomegranited** [comment]
@bmtcril You mentioned that you'd like the OARSy stuff that sits across multiple technologies (like superset and clickhouse) to live in an OARS repo.

Would you like me to turn this repo (openedx-oars) into a tutor plugin (by adding `tutoroars/plugin.py` and files like that), or should I create a new `tutor-contrib-oars` plugin repo?

**Comment by bmtcril** [comment]
Sorry I missed this one. I agree with you about what goes where, in terms of specifics I think we'll probably run into some fun snags along the way but I'd start with:

tutor-contrib-superset:

- All you said
- Configuration to talk to a shared Tutor mysql (where are creds created / stored?)
- Configuration to talk to a shared Tutor cache (redis, right? here are creds created / stored?)
- Presumably uses database info from the LMS settings?
- Set up SSO into LMS w/custom code and config to support our default permissions scheme
- Any additional customized code / templates that can't be installed via OARS?

tutor-contrib-clickhouse: 

- All you said
- Permissions for admin user, an LRS user, and reporting user

tutor-contrib-ralph (new repo, doesn't exist yet):

- Configuration needed to stand up the LRS backended on ClickHouse
- Creates the "xapi" database and any generic table(s) for accepting xAPI events

tutor-contrib-oars (new repo, doesn't exist yet): 

- Creates any necessary downstream tables / views in ClickHouse to support reporting
  - It seems like Ralph is going to start with a very sparse table structure, so we may need to make at least one materialized view to get the data in a performant state
- Creates any Superset datasources needed to talk to Tutor ClickHouse
- Optionally bootstraps Superset with reports
- Optionally bootstraps ClickHouse with test data via xapi-db-load with the `ralph_clickhouse` backend, providing end-to-end testing of the configuration 
  - This currently lives in your tutor-contrib-clickhouse PR, which is good for now, but should probably move here once it exists
- Updates LMS settings to point event-routing-backends to Tutor Ralph
- Eventually updates LMS settings to point any deep links or API URLs to Superset

I think that's everything, only a couple of open questions about which systems own some credentials

**Comment by pomegranited** [comment]
@bmtcril Cool, that clarifies things for me.

> 
> tutor-contrib-superset:
> ...
> * Configuration to talk to a shared Tutor mysql (where are creds created / stored?)

Yep, Superset's MySQL settings default to the LMS's settings here: [host, port, table name, username](https://github.com/open-craft/tutor-contrib-superset/blob/main/tutorsuperset/plugin.py#L23-L27) + [password](https://github.com/open-craft/tutor-contrib-superset/blob/main/tutorsuperset/plugin.py#L44)

> * Configuration to talk to a shared Tutor cache (redis, right? here are creds created / stored?)

Yep, Superset is using Open edX's redis, connection details passed in [here](https://github.com/open-craft/tutor-contrib-superset/blob/main/tutorsuperset/plugin.py#L166-L168) (though looking at that, we might need a `REDIS_USERNAME` too?)

> tutor-contrib-oars (new repo, doesn't exist yet):
> ...
> * Creates any Superset datasources needed to talk to Tutor ClickHouse, using the "reporting" user from tutor-contrib-clickhouse

Cool, yes, that makes sense.

Do you want to cookie-cutter a repo under `openedx` for this? I can start it under `open-craft`, but means we have to move it later.

> * Optionally bootstraps ClickHouse with test data via xapi-db-load ...
>   This currently lives in your tutor-contrib-clickhouse PR, which is good for now, but should probably move here once it exists

Ah ok yes, that's what I was thinking too.

We're on the same page!

**Comment by igobranco** [comment]
About the materialized view.
You can get inspired about what we are doing on [NAU](nau.edu.pt).
We have a couple of materialized views that we use for our analytics. The majority of the queries (except the joins w/ `nau_openedx_extensions_nauuserextendedmodel` table) are compatible with Open edX.
- https://github.com/fccn/nau-database-exporter/blob/master/nau.py

**Comment by bmtcril** [comment]
@pomegranited I think we can call this one done and move on to the more specific issues in the repo. What do you think?
