### ISSUE TITLE
Pull all reports from Insights

### ISSUE THREAD

**Issue by bmtcril** [openedx/openedx-oars#31]
To help build the list of reports needed for OARS we need to go through the Insights code and organize a list of the reports.

Reports in the dashboard should all be listed here: https://github.com/openedx/edx-analytics-dashboard/blob/master/analytics_dashboard/courses/urls.py

Most upstream pipeline code that generates the backing tables is here: https://github.com/openedx/edx-analytics-pipeline

Reports should be labeled into buckets:

- Can be done in OARS v1 with existing xAPI events
- Can be done in OARS v1 with new xAPI events
- Cannot be done in OARS v1

And a level of effort for ones that can be done with existing events:

- Low - can be done in less than a day
- Medium - can be done in one-two days
- High - can be done in a week
- Epic - will likely take more than a week

AC:
- A spreadsheet with all existing Insights events with columns for:
  - Links to their locations in GitHub (in dashboard and any upstream pipeline jobs)
  - The above fields for difficulty and ability to be done with existing events
  - Is the report documented and on by default, or is it one of the "too slow to be run by default" / hidden ones
  - What data sources and tracking event types does this report use?
  - Any notes that may be of interest to the implementer

**Comment by Ian2012** [comment]
Here is a template with the report list https://docs.google.com/spreadsheets/d/1PpnzmJDuZ69P8NMzDCDkwnxyIgwnvmKpIxFnjI-LW7U/edit#gid=0 (**WIP**)

**Comment by bmtcril** [comment]
@Ian2012 are you still doing this task?

**Comment by Ian2012** [comment]
Not currently @bmtcril

**Comment by bmtcril** [comment]
Thanks @Ian2012 , I think I've got it as far as it needs to go. Details on the calculations are included in the Insights docs and we won't have anything like the source data they had, so chasing down all of the links to code is probably not worthwhile. I'm going to call this one done!
