### ISSUE TITLE
Make PyPI packages for all Tutor plugins

### ISSUE THREAD

**Issue by bmtcril** [openedx/openedx-oars#43]
Once we reach a "good enough" state for an alpha release we should make sure the build and release process is working across the repos. This is where the initial work is happening, and may be a good template since they're all pretty similar: https://github.com/openedx/tutor-contrib-oars/pull/13

- [ ] #44
- [ ] #45
- [ ] #46
- [ ] #47

**Comment by mariajgrimaldi** [comment]
Here we added some workflows using for maintenance tasks like this one:
https://github.com/openedx/tutor-contrib-oars/pull/22
https://github.com/openedx/tutor-contrib-clickhouse/pull/11
https://github.com/openedx/tutor-contrib-ralph/pull/10
https://github.com/openedx/tutor-contrib-superset/pull/22

**Comment by Ian2012** [comment]
@bmtcril Is this still needed given that all packages will live in a single repository?

**Comment by bmtcril** [comment]
Nope, I'll close it
